import puppeteer from 'puppeteer';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
const errors = [];
page.on('pageerror', (e) => errors.push('ERR ' + e.message));
page.on('requestfailed', (r) => errors.push('FAIL ' + r.url() + ' :: ' + (r.failure()?.errorText || '?')));
const url = 'http://localhost:4321/docs/tools/pdf-reader.html?pdf=kb/redacted-topic/papers/artgs.pdf&title=ArtGS&embed=1';
await page.goto(url, { waitUntil: 'networkidle0', timeout: 30000 });
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: resolve(__dirname, '..', 'screenshots', 'real', 'pdf-direct.png'), fullPage: false });
const status = await page.evaluate(() => document.getElementById('status')?.textContent || '(no #status)');
console.log('pdf-reader status text:', status);
console.log('errors:', errors);
await browser.close();
